version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://tutoring:password@db:5432/tutoring
    depends_on:
      - db
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./logs:/app/logs

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tutoring
      POSTGRES_USER: tutoring
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
